# version: "3.9"

# services:
#   nextjs:
#     build: .
#     container_name: nextjs
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - ./public/images:/app/public/images
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: madhavam
#       MYSQL_USER: madhavam_user
#       MYSQL_PASSWORD: strongpassword
#     volumes:
#       - mysql_data:/var/lib/mysql

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     restart: always
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./public/images:/app/public/images
#     depends_on:
#       - nextjs

# volumes:
#   mysql_data:


version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: donation_db
      MYSQL_USER: donation_user
      MYSQL_PASSWORD: donation_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - donation_net

  nextjs:
    image: donation-web-next-nextjs
    container_name: nextjs
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - mysql
    networks:
      - donation_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/ssl/letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www/public:ro
    depends_on:
      - nextjs
    networks:
      - donation_net


volumes:
  mysql_data:

networks:
  donation_net:
    driver: bridge
